
import { Product, UserAccount, UserRole } from '../types';
import { usdToGhs } from './currency';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'FY-SH-001',
    name: 'Classic White Shirt',
    description: '100% Cotton premium white shirt',
    priceUsd: 45.00,
    priceGhs: usdToGhs(45.00),
    costUsd: 20.00,
    costGhs: usdToGhs(20.00),
    stock: 50,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/shirt/400/400'
  },
  {
    id: '2',
    sku: 'FY-JN-002',
    name: 'Slim Fit Jeans',
    description: 'Durable blue denim slim fit jeans',
    priceUsd: 89.99,
    priceGhs: usdToGhs(89.99),
    costUsd: 40.00,
    costGhs: usdToGhs(40.00),
    stock: 35,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/jeans/400/400'
  },
  {
    id: '3',
    sku: 'FY-JK-003',
    name: 'Winter Bomber Jacket',
    description: 'Insulated waterproof bomber jacket',
    priceUsd: 120.00,
    priceGhs: usdToGhs(120.00),
    costUsd: 65.00,
    costGhs: usdToGhs(65.00),
    stock: 12,
    category: 'Outerwear',
    image: 'https://picsum.photos/seed/jacket/400/400'
  },
  {
    id: '4',
    sku: 'FY-SN-004',
    name: 'Urban Sneakers',
    description: 'Lightweight breathable mesh sneakers',
    priceUsd: 75.00,
    priceGhs: usdToGhs(75.00),
    costUsd: 35.00,
    costGhs: usdToGhs(35.00),
    stock: 20,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/shoes/400/400'
  },
  {
    id: '5',
    sku: 'FY-TS-005',
    name: 'Graphic T-Shirt',
    description: 'Modern design cotton t-shirt',
    priceUsd: 29.99,
    priceGhs: usdToGhs(29.99),
    costUsd: 12.00,
    costGhs: usdToGhs(12.00),
    stock: 60,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/tshirt/400/400'
  },
  {
    id: '6',
    sku: 'FY-BG-006',
    name: 'Leather Backpack',
    description: 'Premium leather laptop backpack',
    priceUsd: 95.00,
    priceGhs: usdToGhs(95.00),
    costUsd: 45.00,
    costGhs: usdToGhs(45.00),
    stock: 25,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/backpack/400/400'
  },
  {
    id: '7',
    sku: 'FY-HT-007',
    name: 'Baseball Cap',
    description: 'Adjustable cotton baseball cap',
    priceUsd: 22.50,
    priceGhs: usdToGhs(22.50),
    costUsd: 8.00,
    costGhs: usdToGhs(8.00),
    stock: 45,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/cap/400/400'
  },
  {
    id: '8',
    sku: 'FY-SW-008',
    name: 'Wool Sweater',
    description: 'Warm merino wool pullover',
    priceUsd: 78.00,
    priceGhs: usdToGhs(78.00),
    costUsd: 35.00,
    costGhs: usdToGhs(35.00),
    stock: 18,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/sweater/400/400'
  },
  {
    id: '9',
    sku: 'FY-BT-009',
    name: 'Leather Boots',
    description: 'Waterproof hiking boots',
    priceUsd: 135.00,
    priceGhs: usdToGhs(135.00),
    costUsd: 68.00,
    costGhs: usdToGhs(68.00),
    stock: 15,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/boots/400/400'
  },
  {
    id: '10',
    sku: 'FY-SG-010',
    name: 'Sunglasses',
    description: 'UV protection polarized sunglasses',
    priceUsd: 55.00,
    priceGhs: usdToGhs(55.00),
    costUsd: 22.00,
    costGhs: usdToGhs(22.00),
    stock: 30,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/sunglasses/400/400'
  },
  {
    id: '11',
    sku: 'FY-DR-011',
    name: 'Summer Dress',
    description: 'Floral print cotton dress',
    priceUsd: 68.00,
    priceGhs: usdToGhs(68.00),
    costUsd: 30.00,
    costGhs: usdToGhs(30.00),
    stock: 22,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/dress/400/400'
  },
  {
    id: '12',
    sku: 'FY-BL-012',
    name: 'Leather Belt',
    description: 'Genuine leather belt with buckle',
    priceUsd: 38.00,
    priceGhs: usdToGhs(38.00),
    costUsd: 15.00,
    costGhs: usdToGhs(15.00),
    stock: 40,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/belt/400/400'
  },
  {
    id: '13',
    sku: 'FY-HO-013',
    name: 'Hooded Sweatshirt',
    description: 'Fleece-lined pullover hoodie',
    priceUsd: 52.00,
    priceGhs: usdToGhs(52.00),
    costUsd: 24.00,
    costGhs: usdToGhs(24.00),
    stock: 35,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/hoodie/400/400'
  },
  {
    id: '14',
    sku: 'FY-SD-014',
    name: 'Running Shoes',
    description: 'Cushioned running sneakers',
    priceUsd: 98.00,
    priceGhs: usdToGhs(98.00),
    costUsd: 48.00,
    costGhs: usdToGhs(48.00),
    stock: 28,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/running/400/400'
  },
  {
    id: '15',
    sku: 'FY-WL-015',
    name: 'Leather Wallet',
    description: 'Bifold genuine leather wallet',
    priceUsd: 42.00,
    priceGhs: usdToGhs(42.00),
    costUsd: 18.00,
    costGhs: usdToGhs(18.00),
    stock: 50,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/wallet/400/400'
  },
  {
    id: '16',
    sku: 'FY-CT-016',
    name: 'Trench Coat',
    description: 'Classic double-breasted trench',
    priceUsd: 165.00,
    priceGhs: usdToGhs(165.00),
    costUsd: 85.00,
    costGhs: usdToGhs(85.00),
    stock: 8,
    category: 'Outerwear',
    image: 'https://picsum.photos/seed/trench/400/400'
  },
  {
    id: '17',
    sku: 'FY-SK-017',
    name: 'Denim Skirt',
    description: 'High-waisted denim mini skirt',
    priceUsd: 44.00,
    priceGhs: usdToGhs(44.00),
    costUsd: 20.00,
    costGhs: usdToGhs(20.00),
    stock: 26,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/skirt/400/400'
  },
  {
    id: '18',
    sku: 'FY-SC-018',
    name: 'Silk Scarf',
    description: 'Luxury printed silk scarf',
    priceUsd: 58.00,
    priceGhs: usdToGhs(58.00),
    costUsd: 25.00,
    costGhs: usdToGhs(25.00),
    stock: 20,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/scarf/400/400'
  },
  {
    id: '19',
    sku: 'FY-CH-019',
    name: 'Chino Pants',
    description: 'Slim fit cotton chinos',
    priceUsd: 62.00,
    priceGhs: usdToGhs(62.00),
    costUsd: 28.00,
    costGhs: usdToGhs(28.00),
    stock: 32,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/chinos/400/400'
  },
  {
    id: '20',
    sku: 'FY-SD-020',
    name: 'Sandals',
    description: 'Comfortable leather sandals',
    priceUsd: 48.00,
    priceGhs: usdToGhs(48.00),
    costUsd: 22.00,
    costGhs: usdToGhs(22.00),
    stock: 35,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/sandals/400/400'
  },
  {
    id: '21',
    sku: 'FY-GL-021',
    name: 'Winter Gloves',
    description: 'Insulated waterproof gloves',
    priceUsd: 32.00,
    priceGhs: usdToGhs(32.00),
    costUsd: 14.00,
    costGhs: usdToGhs(14.00),
    stock: 28,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/gloves/400/400'
  },
  {
    id: '22',
    sku: 'FY-BZ-022',
    name: 'Blazer',
    description: 'Formal wool blend blazer',
    priceUsd: 148.00,
    priceGhs: usdToGhs(148.00),
    costUsd: 72.00,
    costGhs: usdToGhs(72.00),
    stock: 12,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/blazer/400/400'
  },
  {
    id: '23',
    sku: 'FY-WH-023',
    name: 'Smart Watch',
    description: 'Fitness tracking smartwatch',
    priceUsd: 185.00,
    priceGhs: usdToGhs(185.00),
    costUsd: 95.00,
    costGhs: usdToGhs(95.00),
    stock: 15,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/watch/400/400'
  },
  {
    id: '24',
    sku: 'FY-TK-024',
    name: 'Track Pants',
    description: 'Athletic jogger pants',
    priceUsd: 54.00,
    priceGhs: usdToGhs(54.00),
    costUsd: 25.00,
    costGhs: usdToGhs(25.00),
    stock: 38,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/trackpants/400/400'
  },
  {
    id: '25',
    sku: 'FY-FL-025',
    name: 'Flip Flops',
    description: 'Beach casual flip flops',
    priceUsd: 18.00,
    priceGhs: usdToGhs(18.00),
    costUsd: 7.00,
    costGhs: usdToGhs(7.00),
    stock: 55,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/flipflops/400/400'
  },
  {
    id: '26',
    sku: 'FY-PR-026',
    name: 'Parka Jacket',
    description: 'Heavy-duty winter parka',
    priceUsd: 195.00,
    priceGhs: usdToGhs(195.00),
    costUsd: 98.00,
    costGhs: usdToGhs(98.00),
    stock: 7,
    category: 'Outerwear',
    image: 'https://picsum.photos/seed/parka/400/400'
  },
  {
    id: '27',
    sku: 'FY-TT-027',
    name: 'Tote Bag',
    description: 'Canvas everyday tote bag',
    priceUsd: 38.00,
    priceGhs: usdToGhs(38.00),
    costUsd: 16.00,
    costGhs: usdToGhs(16.00),
    stock: 42,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/tote/400/400'
  },
  {
    id: '28',
    sku: 'FY-PL-028',
    name: 'Polo Shirt',
    description: 'Classic cotton polo',
    priceUsd: 48.00,
    priceGhs: usdToGhs(48.00),
    costUsd: 22.00,
    costGhs: usdToGhs(22.00),
    stock: 44,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/polo/400/400'
  },
  {
    id: '29',
    sku: 'FY-SL-029',
    name: 'Slippers',
    description: 'Memory foam house slippers',
    priceUsd: 28.00,
    priceGhs: usdToGhs(28.00),
    costUsd: 12.00,
    costGhs: usdToGhs(12.00),
    stock: 48,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/slippers/400/400'
  },
  {
    id: '30',
    sku: 'FY-VT-030',
    name: 'Vest',
    description: 'Quilted puffer vest',
    priceUsd: 72.00,
    priceGhs: usdToGhs(72.00),
    costUsd: 34.00,
    costGhs: usdToGhs(34.00),
    stock: 20,
    category: 'Outerwear',
    image: 'https://picsum.photos/seed/vest/400/400'
  },
  {
    id: '31',
    sku: 'FY-BR-031',
    name: 'Bracelet',
    description: 'Silver chain bracelet',
    priceUsd: 45.00,
    priceGhs: usdToGhs(45.00),
    costUsd: 20.00,
    costGhs: usdToGhs(20.00),
    stock: 30,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/bracelet/400/400'
  },
  {
    id: '32',
    sku: 'FY-CR-032',
    name: 'Cardigan',
    description: 'Button-up knit cardigan',
    priceUsd: 65.00,
    priceGhs: usdToGhs(65.00),
    costUsd: 30.00,
    costGhs: usdToGhs(30.00),
    stock: 24,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/cardigan/400/400'
  },
  {
    id: '33',
    sku: 'FY-LF-033',
    name: 'Loafers',
    description: 'Suede casual loafers',
    priceUsd: 88.00,
    priceGhs: usdToGhs(88.00),
    costUsd: 42.00,
    costGhs: usdToGhs(42.00),
    stock: 18,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/loafers/400/400'
  },
  {
    id: '34',
    sku: 'FY-NL-034',
    name: 'Necklace',
    description: 'Gold pendant necklace',
    priceUsd: 68.00,
    priceGhs: usdToGhs(68.00),
    costUsd: 32.00,
    costGhs: usdToGhs(32.00),
    stock: 25,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/necklace/400/400'
  },
  {
    id: '35',
    sku: 'FY-TN-035',
    name: 'Tank Top',
    description: 'Athletic performance tank',
    priceUsd: 24.00,
    priceGhs: usdToGhs(24.00),
    costUsd: 10.00,
    costGhs: usdToGhs(10.00),
    stock: 52,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/tank/400/400'
  },
  {
    id: '36',
    sku: 'FY-WD-036',
    name: 'Windbreaker',
    description: 'Lightweight rain jacket',
    priceUsd: 68.00,
    priceGhs: usdToGhs(68.00),
    costUsd: 32.00,
    costGhs: usdToGhs(32.00),
    stock: 16,
    category: 'Outerwear',
    image: 'https://picsum.photos/seed/windbreaker/400/400'
  },
  {
    id: '37',
    sku: 'FY-HB-037',
    name: 'Handbag',
    description: 'Designer leather handbag',
    priceUsd: 145.00,
    priceGhs: usdToGhs(145.00),
    costUsd: 72.00,
    costGhs: usdToGhs(72.00),
    stock: 12,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/handbag/400/400'
  },
  {
    id: '38',
    sku: 'FY-SH-038',
    name: 'Shorts',
    description: 'Casual cotton shorts',
    priceUsd: 35.00,
    priceGhs: usdToGhs(35.00),
    costUsd: 15.00,
    costGhs: usdToGhs(15.00),
    stock: 40,
    category: 'Apparel',
    image: 'https://picsum.photos/seed/shorts/400/400'
  },
  {
    id: '39',
    sku: 'FY-OX-039',
    name: 'Oxford Shoes',
    description: 'Formal leather oxford shoes',
    priceUsd: 115.00,
    priceGhs: usdToGhs(115.00),
    costUsd: 58.00,
    costGhs: usdToGhs(58.00),
    stock: 14,
    category: 'Footwear',
    image: 'https://picsum.photos/seed/oxford/400/400'
  },
  {
    id: '40',
    sku: 'FY-ER-040',
    name: 'Earrings',
    description: 'Sterling silver drop earrings',
    priceUsd: 52.00,
    priceGhs: usdToGhs(52.00),
    costUsd: 24.00,
    costGhs: usdToGhs(24.00),
    stock: 28,
    category: 'Accessories',
    image: 'https://picsum.photos/seed/earrings/400/400'
  }
];

export const MOCK_USERS: UserAccount[] = [
  {
    id: 'u1',
    name: 'Admin Francisca',
    role: UserRole.ADMIN,
    email: 'admin@famyank.com',
    password: 'Famyank0310'
  },
  {
    id: 'u2',
    name: 'Francisca Worker',
    role: UserRole.WORKER,
    email: 'Francisca@famyank.com',
    passwordSalt: '4Vi26S3auUuf6Qv2mDrlIQ==',
    passwordHash: 'ZX2r3vZrjkJKpp7bBP5DboaPOD+LkA20H2pvpCF9Prg='
  }
];
